<?php

namespace core\mcpe\entity\monster\walking;

use core\Core;

use core\mcpe\entity\{
	MonsterBase,
	Collidable,
	CollisionCheckingTrait,
	CreatureBase
};

use pocketmine\nbt\tag\CompoundTag;

use pocketmine\item\Item;

use pocketmine\level\Position;

use pocketmine\entity\Entity;

class Shulker extends MonsterBase implements Collidable {
	use CollisionCheckingTrait;

    const NETWORK_ID = self::SHULKER;

	public $width = 1.0, $height = 1.0;

    public function initEntity() : void {
        parent::initEntity();
    }

    public function getName() : string {
        return "Shulker";
    }

	public function entityBaseTick(int $tickDiff = 1) : bool {
		return parent::entityBaseTick($tickDiff); // TODO: Change the autogenerated stub
	}

	public static function spawnMob(Position $spawnPos, ?CompoundTag $spawnData = null) : ?CreatureBase {
		//TODO: Implement spawnMob() method.
	}

	public static function spawnFromSpawner(Position $spawnPos, ?CompoundTag $spawnData = null) : ?CreatureBase {
		//TODO: Implement spawnFromSpawner() method.
	}

	public function onCollideWithEntity(Entity $entity) : void {
		//TODO: Implement onCollideWithEntity() method.
	}

    public function getDrops() : array {
        $drops = [];

        if(Core::getInstance()->getMCPE()->drops()) {
            switch(mt_rand(0, 1)) {
                case 0:
                    array_push($drops, Item::get(Item::SHULKER_SHELL, 0, 1));
                break;
            }
        }
        return $drops;
    }
}